#!/bin/sh

CMD="$1"
shift
echo "$@"
PREFIX=/usr
LIBEXEC=${PREFIX}/libexec/xtapp

if test -z $CMD; then
  echo "xtapp command [option [...]]"
  exit 127
fi
if test -e ${LIBEXEC}/${CMD}; then
  ${LIBEXEC}/${CMD} "$@"
  exit $?
else
  echo "xtapp: ${CMD} not found"
  exit 127
fi
