#!/bin/sh

DIR=`dirname $0`
if test -f "$DIR/machikaneyama-setup-gui.py"; then
  python $DIR/machikaneyama-setup-gui.py $HOME
else
  python /usr/share/machikaneyama-setup/machikaneyama-setup-gui.py $HOME
fi
